### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by channg** [OfficialYoungX/paper#1]
```
extends ./includes/layout.pug

block content
  .home-view
    include includes/main.pug
```

**Comment by OfficialYoungX** [comment]
@channg 请问您引用的这段代码是hexo编译过程中输出的吗？还是什么，能否再提供多点报错信息呢。

**Comment by channg** [comment]
@OfficialYoungX 按照readme 创建的新的hexo项目  
把当前项目放进themes文件夹
修改yml 为paper
运行hexo s 

页面会显示上面的报错

**Comment by OfficialYoungX** [comment]
@channg 
在你的blog根目录文件夹下运行：
```bash
npm i hexo-renderer-jade --save
```
然后再 `hexo s` 试试呢

**Comment by channg** [comment]
https://github.com/jerryc127/hexo-theme-butterfly/issues/4
