### ISSUE TITLE
移植了一个平台的版本。

### ISSUE THREAD

**Issue by ruibaby** [OfficialYoungX/paper#6]
主题很漂亮，我移植到了 Halo 平台。

https://github.com/halo-dev/halo-theme-paper

😄

**Comment by OfficialYoungX** [comment]
OK👌过奖了，不过你速度真快😆

**Comment by ruibaby** [comment]
有一个问题奥。

这个 https://github.com/OfficialYoungX/paper/blob/master/layout/page.pug 这个 page 应该是单页面吧，感觉这个有点不像。

**Comment by OfficialYoungX** [comment]
不是单页应用，由于之前基于hexo的。它是基于模版渲染的静态页面，所以不是单页应用。但是其实只要设计在，样式文件在，完全可以开发成单页面。

**Comment by ruibaby** [comment]
嗯。我知道，不过我的意思是 page 这个模板似乎应该是自定义页面，而你这个似乎是调的文章列表。

**Comment by OfficialYoungX** [comment]
啊哈，我懂你的意思了。之前对于page这个页面的用途不是特别清楚，设计的时候也没有考虑到。有时间我再看看。

**Comment by ruibaby** [comment]
好的，那我先 close 这个 issue 了。
