### ISSUE TITLE
一款非常棒的主题！非常感谢！

### ISSUE THREAD

**Issue by GwenXD** [OfficialYoungX/paper#9]
在网上找了很久 Hexo 的主题，都是千篇一律花里胡哨的，看到 paper 的时候瞬间就被惊到了，出淤泥而不染的即视感，希望作者可以继续维护更新(比如美化一下Tags)，继续保持响应迅速、简洁。

**Comment by OfficialYoungX** [comment]
@GwenXD 哈哈，感谢你的认可。有时间我会继续优化细节，改善一下第一版设计的不合理的地方。多谢支持❤️

**Comment by GwenXD** [comment]
嗯嗯！用了快一天，提几个小建议：1.希望优化一下 markdown 表格渲染；2.希望增加父子分类的继承关系显示(现在是父子分类都平铺在「分类」栏内)；3.希望首页可以显示每篇文章的部分内容(可以作为设置项)。继续加油！

**Comment by OfficialYoungX** [comment]
@GwenXD hi，你好。关你提出的"显示每篇文章的部分内容"可以参考[这里](https://hexo.io/zh-cn/docs/tag-plugins#文章摘要和截断)。文章是否显示一部分是你在写文章的时候在markdown里面可以控制的。(我没有提供一个统一的开关设置项，因为你可以在编写文章的时候对于每篇文章有一个更加自由的控制)

**Comment by GwenXD** [comment]
哇非常感谢！

**Comment by OfficialYoungX** [comment]
@GwenXD 你提出的其他建议，我正在修复和完善中哈。

**Comment by OfficialYoungX** [comment]
@GwenXD 
表格渲染已经修复。
`/theme/paper`下运行`git pull`来更新
没什么问题，我就先关闭了。
